services:

  backend:
    build: ./Backend-Pet
    restart: always
    ports:
      - "8000:8000"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pets